name: app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animator: ^3.0.0
  cached_network_image: ^3.0.0
  cloud_firestore: ^2.2.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.2.0
  firebase_core: ^1.2.0
  firebase_storage: ^8.1.0
  flutter_bloc: ^7.0.0
  fluttertoast: ^8.0.6
  geocoding: ^2.0.0
  geolocator: ^7.0.3
  image: ^3.0.2
  image_picker: ^0.7.4
  path_provider: ^2.0.1
  timeago: ^3.0.2
  uuid: ^3.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
